<a href="https://colab.research.google.com/github/chakshumw/House_Sale_Prediction_Logistic_Regression/blob/Colab/House_Sale_Prediction_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

#Apply a fix to the statsmodels library
from scipy import stats
stats.chisqprob = lambda chisq, df: stats.chi2.sf(chisq, df)

In [36]:
data = pd.read_csv('/content/TrustProperty.csv')
data

Price  Resid_area  Air_qual  Num_rooms   Age  Teachers  Poor_prop  \
0     24.0       32.31     0.538      6.575  65.2      24.7       4.98   
1     21.6       37.07     0.469      6.421  78.9      22.2       9.14   
2     34.7       37.07     0.469      7.185  61.1      22.2       4.03   
3     33.4       32.18     0.458      6.998  45.8      21.3       2.94   
4     36.2       32.18     0.458      7.147  54.2      21.3       5.33   
..     ...         ...       ...        ...   ...       ...        ...   
295   28.6       43.92     0.437      6.678  31.1      24.0       6.27   
296   27.1       43.92     0.437      6.549  51.0      24.0       7.39   
297   20.3       43.92     0.437      5.790  58.0      24.0      15.84   
298   22.5       32.24     0.400      6.345  20.1      25.2       4.97   
299   29.0       32.24     0.400      7.041  10.0      25.2       4.74   

     N_hos_beds  N_hot_rooms  Rainfall     Parks Airport  Sold  
0         5.480      11.1920        23  0.049347     Yes     0  
1         7.332      12.1728        42  0.046146      No     1  
2         7.394     101.1200        38  0.045764      No     0  
3         9.268      11.2672        45  0.047151     Yes     0  
4         8.824      11.2896        55  0.039474      No     0  
..          ...          ...       ...       ...     ...   ...  
295       6.972      10.2288        44  0.042031     Yes     0  
296      10.442      10.2168        26  0.045356      No     1  
297       7.606      11.1624        42  0.052079     Yes     0  
298       9.450      13.1800        48  0.036878      No     1  
299       7.980      11.2320        36  0.041376     Yes     1  

[300 rows x 13 columns]

In [37]:
y = data['Sold']
x1 = data[['Price','Resid_area','Air_qual','Num_rooms','Age','Teachers','Poor_prop','N_hos_beds','N_hot_rooms','Rainfall','Parks']]

In [38]:
x = sm.add_constant(x1)
reg_log = sm.Logit(y,x)
results_log = reg_log.fit()
results_log.summary()

Optimization terminated successfully.
         Current function value: 0.581360
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  300
Model:                          Logit   Df Residuals:                      288
Method:                           MLE   Df Model:                           11
Date:                Sun, 17 Nov 2024   Pseudo R-squ.:                  0.1560
Time:                        20:20:57   Log-Likelihood:                -174.41
converged:                       True   LL-Null:                       -206.64
Covariance Type:            nonrobust   LLR p-value:                 1.364e-09
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const          -9.2294      3.481     -2.651      0.008     -16.053      -2.406
Price          -0.2645      0.047     -5.616      0.000      -0.357      -0.172
Resid_area      0.0333      0.030      1.102      0.270      -0.026       0.092
Air_qual       -3.8698      3.368     -1.149      0.251     -10.471       2.731
Num_rooms       1.3218      0.502      2.635      0.008       0.338       2.305
Age             0.0069      0.007      0.931      0.352      -0.008       0.021
Teachers        0.2874      0.075      3.811      0.000       0.140       0.435
Poor_prop      -0.1976      0.045     -4.390      0.000      -0.286      -0.109
N_hos_beds      0.2030      0.084      2.416      0.016       0.038       0.368
N_hot_rooms    -0.0298      0.047     -0.633      0.527      -0.122       0.063
Rainfall        0.0046      0.010      0.451      0.652      -0.016       0.025
Parks          34.6663     31.858      1.088      0.277     -27.773      97.106
===============================================================================
"""

In [39]:
def confusion_matrix(data,actual_values,model):
        pred_values = model.predict(data)
        bins=np.array([0,0.5,1])
        cm = np.histogram2d(actual_values, pred_values, bins=bins)[0]
        accuracy = (cm[0,0]+cm[1,1])/cm.sum()
        return cm, accuracy

In [40]:
cm = confusion_matrix(x,y,results_log)
cm

(array([[118.,  46.],
        [ 51.,  85.]]),
 0.6766666666666666)

In [45]:
data_new = data[['Price','Num_rooms','Poor_prop']]

In [46]:
data_new

Price  Num_rooms  Poor_prop
0     24.0      6.575       4.98
1     21.6      6.421       9.14
2     34.7      7.185       4.03
3     33.4      6.998       2.94
4     36.2      7.147       5.33
..     ...        ...        ...
295   28.6      6.678       6.27
296   27.1      6.549       7.39
297   20.3      5.790      15.84
298   22.5      6.345       4.97
299   29.0      7.041       4.74

[300 rows x 3 columns]

In [47]:
X = sm.add_constant(data_new)
reg_log2 = sm.Logit(y,X)
results_log = reg_log2.fit()
results_log.summary()

Optimization terminated successfully.
         Current function value: 0.626278
         Iterations 5


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  300
Model:                          Logit   Df Residuals:                      296
Method:                           MLE   Df Model:                            3
Date:                Sun, 17 Nov 2024   Pseudo R-squ.:                 0.09075
Time:                        20:22:42   Log-Likelihood:                -187.88
converged:                       True   LL-Null:                       -206.64
Covariance Type:            nonrobust   LLR p-value:                 3.599e-08
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.1079      2.197     -0.049      0.961      -4.414       4.198
Price         -0.1811      0.039     -4.649      0.000      -0.257      -0.105
Num_rooms      0.9246      0.431      2.144      0.032       0.079       1.770
Poor_prop     -0.1371      0.033     -4.159      0.000      -0.202      -0.073
==============================================================================
"""

In [48]:
cm = confusion_matrix(X,y,results_log)
cm

(array([[107.,  57.],
        [ 57.,  79.]]),
 0.62)

In [49]:
results_log.pred_table()

array([[107.,  57.],
       [ 57.,  79.]])

In [50]:
data_all = data_new.copy()

In [56]:
data_all['Airport_mapped'] = data['Airport'].map({'No':0,'Yes':1})

In [57]:
data_all

const  Price  Num_rooms  Poor_prop  Airport_mapped
0      1.0   24.0      6.575       4.98               1
1      1.0   21.6      6.421       9.14               0
2      1.0   34.7      7.185       4.03               0
3      1.0   33.4      6.998       2.94               1
4      1.0   36.2      7.147       5.33               0
..     ...    ...        ...        ...             ...
295    1.0   28.6      6.678       6.27               1
296    1.0   27.1      6.549       7.39               0
297    1.0   20.3      5.790      15.84               1
298    1.0   22.5      6.345       4.97               0
299    1.0   29.0      7.041       4.74               1

[300 rows x 5 columns]

In [58]:
data_final = sm.add_constant(data_all)
reg_log = sm.Logit(y,data_final)
results_log = reg_log.fit()
results_log.summary()

Optimization terminated successfully.
         Current function value: 0.625240
         Iterations 5


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  300
Model:                          Logit   Df Residuals:                      295
Method:                           MLE   Df Model:                            4
Date:                Sun, 17 Nov 2024   Pseudo R-squ.:                 0.09226
Time:                        20:27:46   Log-Likelihood:                -187.57
converged:                       True   LL-Null:                       -206.64
Covariance Type:            nonrobust   LLR p-value:                 1.055e-07
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
const             -0.1113      2.200     -0.051      0.960      -4.422       4.200
Price             -0.1782      0.039     -4.563      0.000      -0.255      -0.102
Num_rooms          0.9273      0.431      2.149      0.032       0.082       1.773
Poor_prop         -0.1339      0.033     -4.047      0.000      -0.199      -0.069
Airport_mapped    -0.2010      0.255     -0.790      0.430      -0.700       0.298
==================================================================================
"""

In [70]:
data_all

const  Price  Num_rooms  Poor_prop  Airport_mapped
0      1.0   24.0      6.575       4.98               1
1      1.0   21.6      6.421       9.14               0
2      1.0   34.7      7.185       4.03               0
3      1.0   33.4      6.998       2.94               1
4      1.0   36.2      7.147       5.33               0
..     ...    ...        ...        ...             ...
295    1.0   28.6      6.678       6.27               1
296    1.0   27.1      6.549       7.39               0
297    1.0   20.3      5.790      15.84               1
298    1.0   22.5      6.345       4.97               0
299    1.0   29.0      7.041       4.74               1

[300 rows x 5 columns]

In [74]:
test_data = pd.read_csv('/content/TrustProperty_Test.csv')
test_data

Price  Num_rooms  Poor_prop  Airport  Sold
0    9.6      6.461      18.05        1     0
1    8.2      6.152      26.45        0     1
2    8.4      5.935      34.02        1     0
3   12.8      5.627      22.88        1     0
4   10.5      5.818      22.11        0     1
5   17.1      6.406      19.52        1     0
6   14.8      6.219      16.59        0     0
7   15.4      6.485      18.85        0     0
8   10.8      5.854      23.79        0     0
9   11.8      6.459      23.98        1     0

In [75]:
test_actual = test_data['Sold']
test_data = test_data.drop(['Sold'], axis = 1)
test_data = sm.add_constant(test_data)

In [76]:
test_data

const  Price  Num_rooms  Poor_prop  Airport
0    1.0    9.6      6.461      18.05        1
1    1.0    8.2      6.152      26.45        0
2    1.0    8.4      5.935      34.02        1
3    1.0   12.8      5.627      22.88        1
4    1.0   10.5      5.818      22.11        0
5    1.0   17.1      6.406      19.52        1
6    1.0   14.8      6.219      16.59        0
7    1.0   15.4      6.485      18.85        0
8    1.0   10.8      5.854      23.79        0
9    1.0   11.8      6.459      23.98        1

In [72]:
test_data

Price  Num_rooms  Poor_prop  Airport
0    9.6      6.461      18.05        1
1    8.2      6.152      26.45        0
2    8.4      5.935      34.02        1
3   12.8      5.627      22.88        1
4   10.5      5.818      22.11        0
5   17.1      6.406      19.52        1
6   14.8      6.219      16.59        0
7   15.4      6.485      18.85        0
8   10.8      5.854      23.79        0
9   11.8      6.459      23.98        1

In [77]:
cm = confusion_matrix(test_data,test_actual,results_log)
cm

(array([[3., 5.],
        [0., 2.]]),
 0.5)

In [78]:
cm_df = pd.DataFrame(cm[0])
cm_df.columns = ['Predicted 0','Predicted 1']
cm_df = cm_df.rename(index={0: 'Actual 0',1:'Actual 1'})
cm_df

Predicted 0  Predicted 1
Actual 0          3.0          5.0
Actual 1          0.0          2.0

In [79]:
print ('Missclassification rate: '+str((5+0)/10))

Missclassification rate: 0.5
